# Generated by Django 3.1.7 on 2021-04-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20210405_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
