# Generated by Django 3.1.7 on 2021-04-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_dog_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
