# Generated by Django 3.1.7 on 2021-04-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_auto_20210405_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizResults',
            new_name='QuizResult',
        ),
    ]
