# Generated by Django 3.1.7 on 2021-04-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_quizresult_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
